when:
  - event: push
    branch: main

labels:
  platform: linux/amd64

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true
      depth: 0

depends_on:
  - test
  - commits

steps:
  - name: bump-version
    image: ghcr.io/cocogitto/cog:latest
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - git config user.name "Woodpecker CI"
      - git config user.email "ci@barrywalker.io"
      - git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/${CI_REPO}.git"
      - cog bump --auto && git push --follow-tags || echo "No version bump needed"
      - echo "Current version:" && cog get-version
